import { randomUUID } from 'crypto';
import dotenv from 'dotenv';
// Load env vars
dotenv.config();

import { PaperExecutionEngine } from '../src/engine/PaperExecutionEngine';
import { supabase } from '../src/utils/supabaseClient';

async function runE2E() {
    console.log("🚀 Starting E2E Dry-Run Simulation for L4/L5 & Supabase");

    // Fetch a valid user_id to prevent FK violation
    const { data: users } = await supabase.from('paper_account').select('user_id').limit(1);
    const userId = (users && users.length > 0) ? users[0].user_id : '00000000-0000-0000-0000-000000000000';
    
    console.log(`[E2E] Simulating session for User ID: ${userId}\n`);

    // 1. Instanciate L4-A (PaperExecutionEngine)
    const engine = new PaperExecutionEngine(userId);
    
    // Wait for the memory state to load
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Artificially increase margin to avoid 'Insufficient Margin' rejection due to legacy positions
    if (engine.accounts['crypto']) {
        engine.accounts['crypto'].balance += 100000;
        console.log(`[E2E] Artificially inflated balance to $${engine.accounts['crypto'].balance} to bypass margin limits.`);
    }

    // 2. Open a Mock Position
    console.log(`▶️ [Step 1] Opening mock trade via Engine (simulating L3 Approval)...`);
    const symbol = "MOCKBTC/USDT";
    await engine.openPosition({
        symbol,
        exchange: "Hyperliquid",
        side: "LONG",
        entryPrice: 60000,
        notionalValue: 1000,
        leverage: 5,
        stopLoss: 59000,
        takeProfit: 62000,
        rationale: "Testing E2E Pipeline with Supabase User Scoping",
        openedBy: "L3_E2E_Test",
    });

    const pos = engine.getOpenPositionsSnapshot().find((p: any) => p.symbol === symbol);
    if (!pos) {
        throw new Error("❌ Failed to open position in Engine.");
    }
    console.log(`✅ Trade opened with ID: ${pos.id}`);

    // 3. Inject ticks passing Break-Even trigger (If method available in your engine)
    console.log(`\n▶️ [Step 2] Simulating Trade Active Phase (Waiting 3 seconds)...`);
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    console.log(`\n▶️ [Step 3] Forcing Close to trigger L5 PostTradeLogger...`);
    // Close at loss/win -> triggers postTradeLogger auto autopsy in PaperEngine
    await engine.closePosition(pos.id, 59500, "CLOSED_SL");

    // Wait a brief moment for the async logging (PostTradeLogger execution)
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    console.log(`\n▶️ [Step 4] Triggering L5 Forensic Batch Request (Weekend Simulation)...`);
    // Import L5 dynamically to avoid premature startup side-effects
    const { L5QuantitativeResearcher } = await import('../src/engine/L5_quantitative_researcher');
    await L5QuantitativeResearcher.runFullWeekendAnalysis(userId);

    // Wait for Vector DB embeddings and insertions
    await new Promise(resolve => setTimeout(resolve, 4000));

    console.log(`\n▶️ [Step 5] Verifying Supabase Database Tables (RLS Check)...`);
    
    // Check Autopsies Table
    const { data: autopsies, error: autopsiesErr } = await supabase
        .from('trade_autopsies')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false })
        .limit(1);

    if (autopsiesErr) {
        console.error("❌ E2E Failed: Supabase Autopsies Error:", autopsiesErr.message);
    } else if (!autopsies || autopsies.length === 0) {
        console.error("❌ E2E Failed: No autopsy found in Supabase. Check PostTradeLogger SQL query.");
    } else {
        console.log("✅ PostTradeLogger validated! Autopsy successfully recorded:");
        console.log(`   ID: ${autopsies[0].id}`);
        console.log(`   R-Multiple: ${autopsies[0].r_multiple}`);
        console.log(`   Realized PNL: ${autopsies[0].realized_pnl}`);
    }
    
    // Check Vector Memory Table
    const { data: memory, error: memoryErr } = await supabase
        .from('trade_memory')
        .select('lesson_learned, mistake_category, market_regime')
        .eq('user_id', userId)
        .order('created_at', { ascending: false })
        .limit(1);

    if (memoryErr) {
         console.error("❌ E2E Failed: Supabase Memory Error:", memoryErr.message);
    } else if (!memory || memory.length === 0) {
         console.log("⚠️ E2E Warning: No memory generated by L5. This is normal if there was no 'Alpha Decay' or severe flaw detected.");
    } else {
         console.log("✅ VectorMemoryManager validated! Evolutionary Path / Memory successfully stored:");
         console.log(`   Mistake: ${memory[0].mistake_category}`);
         console.log(`   Regime: ${memory[0].market_regime}`);
         console.log(`   Lesson: ${memory[0].lesson_learned?.substring(0, 50)}...`);
    }

    console.log("\n🚀 E2E Simulation Finished!");
    process.exit(0);
}

runE2E().catch(err => {
    console.error("E2E FATAL:", err);
    process.exit(1);
});
